### ISSUE TITLE
import文の書き方の修正と 一部のディレクトリ名変更を行いたい

### ISSUE THREAD

**Issue by Issei-Hiramatsu** [natsuki120/vantan_connect#51]
import文
elements配下など複雑になる場合など以外は
import 'package:vantan_connect/component/shered/single/color.dart';   ->.  import '../../shered/single/buttons.dart';　
import 'package:vantan_connect/component/local/attendance_modal_with_reason/elements/checkbox_with_class.dart';
->.   import 'elements/checkbox_with_class.dart';

indexを見た際にimport文でどのようなelementsを使用しているかを確認したい場合に必要以上に冗長だと、
atomicDesignからtreeDesignに移行した意味が薄いと感じたため。
完全に好みになってしまうのですが、少し思ったのでご指摘いただけると幸いです。
一応domain elements 外部パッケージごとにimport文が書けるので読みやすくは個人的にはなると考えています。

shered は sharedに test_styleはtext_styleに変更しておきます。

合意が取れれば10分もあれば実施可能です。反映箇所はtreeDesignを元にしているのでそこにプルリクを行います。

**Comment by natsuki120** [comment]
そうしよう
惰性でやってたから意識してなかったわ

その方針でいきましょう
